#!/bin/bash

function prepend_dir() {
  local var="$1"
  local dir="$2"
  if [ -d "$dir" ]; then
    eval "export $var=\"\$dir\${$var:+:\$$var}\""
  fi
}

function append_dir() {
  local var="$1"
  local dir="$2"
  if [ -d "$dir" ]; then
    eval "export $var=\"\${$var:+\$$var:}\$dir\""
  fi
}

if [ "$SNAP_ARCH" == "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" == "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" == "arm64" ]; then
  ARCH="aarch64-linux-gnu"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

append_dir LOCPATH "$SNAP/usr/lib/locale"

# export CFLAGS="-I$SNAP/usr/include/$ARCH -I$SNAP/usr/include -I$SNAP/include/$ARCH -I$SNAP/include"
# export CXXFLAGS="$CFLAGS"
export LDFLAGS="-L$SNAP/usr/lib -L$SNAP/usr/lib/$ARCH -L$SNAP/lib -L$SNAP/lib/$ARCH"
# export SWIG_LIB="$SNAP/usr/share/swig3.0"

source "/opt/mycroft/.venv/bin/activate"

CMD="$1"; shift;
[ -z "$CMD" ] && CMD="all"

snapcraft-preload /opt/mycroft/start-mycroft.sh "$CMD" "$@"
